In [1]:
from __future__ import print_function
import binascii
import struct
from PIL import Image
import numpy as np
import scipy
import scipy.misc
import scipy.cluster

In [3]:
NUM_CLUSTERS = 5

print('reading image')
im = Image.open('red_shirt.jpeg')
im = im.resize((150, 150))      # optional, to reduce time
ar = np.asarray(im)
shape = ar.shape
ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)

print('finding clusters')
codes, dist = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
print('cluster centres:\n', codes)

vecs, dist = scipy.cluster.vq.vq(ar, codes)         # assign codes
counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences

index_max = scipy.argmax(counts)                    # find most frequent
peak = codes[index_max]
colour = binascii.hexlify(bytearray(int(c) for c in peak)).decode('ascii')
print('most frequent is %s (#%s)' % (peak, colour))

reading image
finding clusters


/var/folders/kn/d6m3n8r52vd4544z7x_6p0dm0000gp/T/ipykernel_51057/2498064813.py:8: DeprecationWarning: scipy.product is deprecated and will be removed in SciPy 2.0.0, use numpy.product instead
  ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)


cluster centres:
 [[202.77458519   0.82840955  30.0070147 ]
 [254.48767663 254.49282506 254.43706868]
 [208.45780051   0.76434052  35.37431494]
 [233.45327103 177.62616822 179.0046729 ]
 [214.22592593  91.76666667 100.62592593]]
most frequent is [254.48767663 254.49282506 254.43706868] (#fefefe)


/var/folders/kn/d6m3n8r52vd4544z7x_6p0dm0000gp/T/ipykernel_51057/2498064813.py:15: DeprecationWarning: scipy.histogram is deprecated and will be removed in SciPy 2.0.0, use numpy.histogram instead
  counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences
/var/folders/kn/d6m3n8r52vd4544z7x_6p0dm0000gp/T/ipykernel_51057/2498064813.py:17: DeprecationWarning: scipy.argmax is deprecated and will be removed in SciPy 2.0.0, use numpy.argmax instead
  index_max = scipy.argmax(counts)                    # find most frequent


In [5]:
from colorthief import ColorThief

ModuleNotFoundError: No module named 'colorthief'

In [4]:
color_thief = ColorThief('red_shirt.jpeg')
# get the dominant color
dominant_color = color_thief.get_color(quality=1)
print(dominant_color)
palette = color_thief.get_palette(color_count=6)
print(palette)

ModuleNotFoundError: No module named 'colorthief'